export namespace Flag {
  export const CEREBRAS_AUTO_SHARE = truthy("CEREBRAS_AUTO_SHARE")
  export const CEREBRAS_CONFIG = process.env["CEREBRAS_CONFIG"]
  export const CEREBRAS_CONFIG_DIR = process.env["CEREBRAS_CONFIG_DIR"]
  export const CEREBRAS_CONFIG_CONTENT = process.env["CEREBRAS_CONFIG_CONTENT"]
  export const CEREBRAS_DISABLE_AUTOUPDATE = truthy("CEREBRAS_DISABLE_AUTOUPDATE")
  export const CEREBRAS_DISABLE_PRUNE = truthy("CEREBRAS_DISABLE_PRUNE")
  export const CEREBRAS_PERMISSION = process.env["CEREBRAS_PERMISSION"]
  export const CEREBRAS_DISABLE_DEFAULT_PLUGINS = truthy("CEREBRAS_DISABLE_DEFAULT_PLUGINS")
  export const CEREBRAS_DISABLE_LSP_DOWNLOAD = truthy("CEREBRAS_DISABLE_LSP_DOWNLOAD")
  export const CEREBRAS_ENABLE_EXPERIMENTAL_MODELS = truthy("CEREBRAS_ENABLE_EXPERIMENTAL_MODELS")
  export const CEREBRAS_DISABLE_AUTOCOMPACT = truthy("CEREBRAS_DISABLE_AUTOCOMPACT")
  export const CEREBRAS_FAKE_VCS = process.env["CEREBRAS_FAKE_VCS"]
  export const CEREBRAS_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH =
    process.env["CEREBRAS_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH"]

  // Experimental
  export const CEREBRAS_EXPERIMENTAL = truthy("CEREBRAS_EXPERIMENTAL")
  export const CEREBRAS_EXPERIMENTAL_WATCHER = CEREBRAS_EXPERIMENTAL || truthy("CEREBRAS_EXPERIMENTAL_WATCHER")

  function truthy(key: string) {
    const value = process.env[key]?.toLowerCase()
    return value === "true" || value === "1"
  }
}
